MilLog/MilAccBook/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from .models import Document, DocumentProduct, JournalLine, OperationSubline, Peer, Product, ProductGroup, ProductVariant
from .views import AssetGroupView, AssetView, DocumentCreateView, ProductsView, ProductVariantView

urlpatterns = [
    path("document/", ListView.as_view(model=Document), name='documents'),
    path("document/add/", DocumentCreateView.as_view(), name='document-create'),
    #path("document/<int:pk>/", UpdateView.as_view(model=Document)),
    path('document/<int:pk>/', DetailView.as_view(model=Document), name='document-detail'),
    path("documentproduct/", ListView.as_view(model=DocumentProduct), name='documentproducts'),
    path("documentproduct/add/", CreateView.as_view(model=DocumentProduct, fields=['document', 'product_variant', 'total_q', 'sort1_q', 'sort2_q', 'sort3_q', 'sort4_q', 'sort5_q'], success_url=reverse_lazy('documentproducts')), name='documentproduct-create'),
    path("journalline/", ListView.as_view(model=JournalLine), name='journallines'),
    path("journalline/add/", CreateView.as_view(model=JournalLine, fields=['record_date', 'document_product'], success_url=reverse_lazy('journallines')), name='operationsubline-create'),
    path("operationsubline/", ListView.as_view(model=OperationSubline), name='operationsublines'),
    path("operationsubline/add/", CreateView.as_view(model=OperationSubline, fields=['operation', 'peer', 'document_product', 'total_q', 'sort1_q', 'sort2_q', 'sort3_q', 'sort4_q', 'sort5_q'], success_url=reverse_lazy('operationsublines')), name='operationsubline-create'),
    path("peer/", ListView.as_view(model=Peer), name='peers'),
    path("peer/add/", CreateView.as_view(model=Peer, fields=['name'], success_url=reverse_lazy('peers')), name='peer-create'),
    path("product/", ProductsView.as_view(), name='products'),
    path("product/add/", CreateView.as_view(model=Product, fields=['name', 'has_sort', 'uom', 'group'], success_url=reverse_lazy('products')), name='product-create'),
    path("product_variant/", ListView.as_view(model=ProductVariant), name='productvariants'),
    path("product_variant/<int:pk>/", DetailView.as_view(model=ProductVariant)),
    path("product_variant/add/", CreateView.as_view(model=ProductVariant, fields=['product', 'price'], success_url=reverse_lazy('productvariants')), name='productvariant-create'),
    path("pv_page/<int:pv_id>", ProductVariantView.pv_page),
    path("asset", AssetView.asset_page),
    path("productgroup/", ListView.as_view(model=ProductGroup), name='productgroups'),
    path("productgroup/add/", CreateView.as_view(model=ProductGroup, fields=['name', 'parent'], success_url=reverse_lazy('productgroups')), name='productgroup-create'),
    path("assetgroup", AssetGroupView.asset_page),
]

MilLog/MilLog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('MilAccBook.urls'))
]

MilLog/MilAccBook/models.py
"""
Definition of models.
"""

from random import choices
from sre_constants import CATEGORY_DIGIT
from django.db import models

class Peer(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class ProductGroup(models.Model):
    name = models.CharField(max_length=200)
    parent = models.ForeignKey("self", on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name

PRODUCT_UNIT_OF_MEASURE = (
    (1, "Kilogramm"), # Кілограм
    (2, "Piece"),     # Штука
    (3, "Kit"),       # Комплект
    (4, "Box"),       # Коробка
    (5, "Pack"),      # Пачка
    )

def UOM_STR(uom_id):
    if uom_id == 1:
        return 'кг'
    elif uom_id == 2:
        return 'шт'
    elif uom_id == 3:
        return 'к-т'
    elif uom_id == 4:
        return 'коробка'
    elif uom_id == 5:
        return 'пачка'
    else:
        return 'UNKNOWN'

class Product(models.Model):
    name = models.CharField(max_length=200)
    has_sort = models.BooleanField()
    uom = models.IntegerField(choices=PRODUCT_UNIT_OF_MEASURE)

    group = models.ForeignKey(ProductGroup, on_delete=models.CASCADE)

    def uom_str(self):
        return UOM_STR(self.uom)

class ProductVariant(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.FloatField()
    # sort = models.IntegerField()

class ComplexQuantity:
    #total_q = models.FloatField()
    #sort1_q = models.FloatField()
    #sort2_q = models.FloatField()
    #sort3_q = models.FloatField()
    #sort4_q = models.FloatField()
    #sort5_q = models.FloatField()

    #def __init__(self):
    #    self.total_q = 0.0
    #    self.sort1_q = 0.0
    #    self.sort2_q = 0.0
    #    self.sort3_q = 0.0
    #    self.sort4_q = 0.0
    #    self.sort5_q = 0.0

    def __init__(self, total_q=0.0, sort1_q=0.0, sort2_q=0.0, sort3_q=0.0, sort4_q=0.0, sort5_q=0.0):
        self.total_q = total_q
        self.sort1_q = sort1_q
        self.sort2_q = sort2_q
        self.sort3_q = sort3_q
        self.sort4_q = sort4_q
        self.sort5_q = sort5_q

    def increase(self, value):
        #print('+++ (' + str(self.total_q) + '+' + str(value.total_q) + ')=(' + str(self.sort1_q) + '+' + str(value.sort1_q) + ')+(' + str(self.sort2_q) + '+' + str(value.sort2_q) + ')+(' + str(self.sort3_q) + '+' + str(value.sort3_q) + ')+(' + str(self.sort4_q) + '+' + str(value.sort4_q) + ')+(' + str(self.sort5_q) + '+' + str(value.sort5_q) + ')')
        self.total_q += value.total_q
        self.sort1_q += value.sort1_q
        self.sort2_q += value.sort2_q
        self.sort3_q += value.sort3_q
        self.sort4_q += value.sort4_q
        self.sort5_q += value.sort5_q

        return self

    def decrease(self, value):
        #print('--- (' + str(self.total_q) + '-' + str(value.total_q) + ')=(' + str(self.sort1_q) + '-' + str(value.sort1_q) + ')+(' + str(self.sort2_q) + '-' + str(value.sort2_q) + ')+(' + str(self.sort3_q) + '-' + str(value.sort3_q) + ')+(' + str(self.sort4_q) + '-' + str(value.sort4_q) + ')+(' + str(self.sort5_q) + '-' + str(value.sort5_q) + ')')
        self.total_q -= value.total_q
        self.sort1_q -= value.sort1_q
        self.sort2_q -= value.sort2_q
        self.sort3_q -= value.sort3_q
        self.sort4_q -= value.sort4_q
        self.sort5_q -= value.sort5_q

        return self

COMPLEX_OPERATION = 1
EXTERNAL_TRANSFER = 2
INTERNAL_TRANSFER = 3
CATEGORY_CHANGE = 4
OPERATION_TYPE = (
        (COMPLEX_OPERATION, "Complex operation"),
        (EXTERNAL_TRANSFER, "External transfer"),
        (INTERNAL_TRANSFER, "Internal transfer"),
        (CATEGORY_CHANGE, "Category change")
    )
class Document(models.Model):
    name = models.CharField(max_length=200)
    number = models.CharField(max_length=200)
    date = models.DateField()
    operation = models.IntegerField(choices=OPERATION_TYPE)
    peer = models.ForeignKey(Peer, on_delete=models.CASCADE)
    base_document = models.ForeignKey('self', null=True, on_delete=models.CASCADE)
    base_document_str = models.CharField(max_length=200, null=True, blank=True)

class DocumentProduct(models.Model):
    document = models.ForeignKey(Document, on_delete=models.CASCADE)
    product_variant = models.ForeignKey(ProductVariant, on_delete=models.CASCADE)

    total_q = models.FloatField()
    sort1_q = models.FloatField(default=0)
    sort2_q = models.FloatField(default=0)
    sort3_q = models.FloatField(default=0)
    sort4_q = models.FloatField(default=0)
    sort5_q = models.FloatField(default=0)

    @property
    def operation_q(self):
        return ComplexQuantity(total_q=self.total_q, sort1_q=self.sort1_q, sort2_q=self.sort2_q, sort3_q=self.sort3_q, sort4_q=self.sort4_q, sort5_q=self.sort5_q)

    #   set { TotalQuantity = value.TotalQuantity; Sort1Quantity = value.Sort1Quantity; Sort2Quantity = value.Sort2Quantity; Sort3Quantity = value.Sort3Quantity; Sort4Quantity = value.Sort4Quantity; Sort5Quantity = value.Sort5Quantity; }

    #    public virtual ICollection<OperationSubline> OperationSublines { get; private set; } =
    #        new ObservableCollection<OperationSubline>();

class OperationSubline(models.Model):
    operation = models.IntegerField(choices=OPERATION_TYPE)
    peer = models.ForeignKey(Peer, on_delete=models.CASCADE)
    document_product = models.ForeignKey(DocumentProduct, on_delete=models.CASCADE)

    total_q = models.FloatField()
    sort1_q = models.FloatField(default=0)
    sort2_q = models.FloatField(default=0)
    sort3_q = models.FloatField(default=0)
    sort4_q = models.FloatField(default=0)
    sort5_q = models.FloatField(default=0)

    @property
    def operation_q(self):
        return ComplexQuantity(total_q=self.total_q, sort1_q=self.sort1_q, sort2_q=self.sort2_q, sort3_q=self.sort3_q, sort4_q=self.sort4_q, sort5_q=self.sort5_q)
    #   set { TotalQuantity = value.TotalQuantity; Sort1Quantity = value.Sort1Quantity; Sort2Quantity = value.Sort2Quantity; Sort3Quantity = value.Sort3Quantity; Sort4Quantity = value.Sort4Quantity; Sort5Quantity = value.Sort5Quantity; }

class JournalLine(models.Model):
    record_date = models.DateField()
    document_product = models.ForeignKey(DocumentProduct, on_delete=models.CASCADE)
    

MilLog/MilAccBook/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))

MilLog/MilAccBook/templates/MilAccBook/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

MilLog/MilAccBook/templates/MilAccBook/document_detail.html
{% block content %}
<p>Документ {{ object.pk }}: {{ object.name }} №{{ object.number }} від {{ object.date }}</p>
<p>Підстава (мета): {{ object.base_document_str }}</p>
<p>Тип операції документа: {{ object.operation }}</p>
<p>Контрагент: {{ object.peer.name }}</p>
<table>
	<tr>
		<th>№ з/п</th>
		<th>Найменування</th>
		<th>Одиниця виміру</th>
		<th>Кількість</th>
		<th>Проведено</th>
	</tr>
{% for document_product in object.documentproduct_set.all %}
	<tr>
		<td>{{ forloop.counter }}</td>
		<td>{{ document_product.product_variant.product.name }} ({{ document_product.product_variant.price }} грн)</td>
		<td>{{ document_product.product_variant.product.uom_str }}</td>
		<td>{{ document_product.total_q }}</td>
		<td>{{ document_product.journalline_set.first.record_date }}</td>
	</tr>
{% endfor %}
</table>
{% endblock %}

MilLog/MilAccBook/templates/MilAccBook/document_form.html
{% block content %}
<form action="." method="POST">
	{% csrf_token %}
	{{ form.as_div }}
	<button type="submit">SUBMIT</button>
</form>
{% endblock %}

MilLog/MilAccBook/templates/MilAccBook/document_list.html
{% block content %}
<h1>Document List</h1>
  {% if document_list %}
<ul>
    <table>
        <tr>
            <th>ID</th>
            <th>Document date</th>
            <th>Document name</th>
            <th>Document number</th>
            <th>Operation</th>
            <th>Peer</th>
            <th>Base document</th>
            <th>Base document --</th>
        </tr>
    {% for document in document_list %}
        <tr>
            <td><a href="{{ document.get_absolute_url }}{{ document.pk }}/">{{ document.pk }}</a></td>
            <td>{{ document.date }}</td>
            <td>{{ document.name }}</td>
            <td>{{ document.number}} </td>
            <td>{{ document.operation }}</td>
            <td>{{ document.peer.name }}</td>
            <td>{{ document.base_document }}</td>
            <td>{{ document.base_document_str }}</td>
        </tr>
    {% endfor %}
    </table>
  {% else %}
<p>There are no documents in the book.</p>
  {% endif %}
{% endblock %}

MilLog/MilAccBook/templates/MilAccBook/documentproduct_form.html
{% block content %}
<form action="." method="POST">
	{% csrf_token %}
	{{ form.as_div }}
	<button type="submit">SUBMIT</button>
</form>
{% endblock %}

MilLog/MilAccBook/templates/MilAccBook/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - My Django Application</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Application name</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'contact' %}">Contact</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - My Django Application</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

MilLog/MilAccBook/templates/MilAccBook/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout/" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log in</a></li>
</ul>

{% endif %}

MilLog/MilAccBook/templates/MilAccBook/operationsubline_form.html
{% block content %}
<form action="." method="POST">
	{% csrf_token %}
	{{ form.as_div }}
	<button type="submit">SUBMIT</button>
</form>
{% endblock %}

MilLog/MilAccBook/templates/MilAccBook/operationsubline_list.html
{% block content %}
<h1>Operation Subline List</h1>
  {% if operationsubline_list %}
<ul>
    {% for osl in operationsubline_list %}
    <li>
        <a href="{{ osl.get_absolute_url }}{{ osl.pk }}">{{ osl.operation }} {{ osl.peer.name }} {{ osl.document_product.pk }} {{ osl.total_q }}</a>
    </li>
    {% endfor %}
</ul>
  {% else %}
<p>There are no products in the book.</p>
  {% endif %}
{% endblock %}

MilLog/MilAccBook/templates/MilAccBook/peer_form.html
{% block content %}
<form action="." method="POST">
	{% csrf_token %}
	{{ form.as_div }}
	<button type="submit">SUBMIT</button>
</form>
{% endblock %}

MilLog/MilAccBook/templates/MilAccBook/peer_list.html
{% block content %}
<h1>Peer List</h1>
  {% if peer_list %}
<ul>
    {% for peer in peer_list %}
    <li>
        <a href="{{ peer.get_absolute_url }}{{ peer.pk }}">{{ peer.name }}</a>
    </li>
    {% endfor %}
</ul>
  {% else %}
<p>There are no peers in the book.</p>
  {% endif %}
{% endblock %}

MilLog/MilAccBook/templates/MilAccBook/productgroup_form.html
{% block content %}
<form action="." method="POST">
	{% csrf_token %}
	{{ form.as_div }}
	<button type="submit">SUBMIT</button>
</form>
{% endblock %}

MilLog/MilAccBook/templates/MilAccBook/productgroup_list.html
{% block content %}
<h1>ProductGroup List</h1>
  {% if productgroup_list %}
<ul>
    {% for productgroup in productgroup_list %}
    <li>
        <a href="{{ productgroup.get_absolute_url }}{{ productgroup.pk }}">{{ productgroup.name }}</a>
    </li>
    {% endfor %}
</ul>
  {% else %}
<p>There are no product groups in the book.</p>
  {% endif %}
{% endblock %}

MilLog/MilAccBook/templates/MilAccBook/productvariant_detail.html
{% block content %}
<h1>{{ object.product.name }}</h1>
<p>{{ object.price }}</p>
<p><a href="../../pv_page/{{ object.pk }}">Product variant page</a></p>
{% endblock %}